#!/bin/sh
# /etc/lightdm/Xsession - Launch X session with D-Bus environment
[ -f /etc/profile ] && . /etc/profile
[ -f "$HOME/.profile" ] && . "$HOME/.profile"

if [ -z "$1" ]; then
    exec dbus-run-session -- startxfce4
elif [ -z "$DBUS_SESSION_BUS_ADDRESS" ] && command -v dbus-run-session >/dev/null 2>&1; then
    exec dbus-run-session -- "$@"
else
    exec "$@"
fi
