# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
# restartNowMode:
#  - user-checked  - offer the option, check it by default
#  - user-unchecked - offer the option, leave it unchecked
#  - always        - don't offer the option, just reboot
restartNowMode: user-checked

# Command to execute when the user asks to reboot
restartNowCommand: "shutdown -r now"
