# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
crypttabOptions:            luks
mountOptions:
    - filesystem: default
      options: [ defaults, noatime ]
    - filesystem: efi
      options: [ defaults, noatime, umask=0077 ]
    - filesystem: btrfs
      options: [ defaults, noatime, compress=zstd:3, ssd, discard=async ]
    - filesystem: ext4
      options: [ defaults, noatime ]
