# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# Configuration for the grubcfg module.
---
overwrite: true
prefer_grub_d: false
keepDistributor: false

kernel_params: [ "quiet", "splash" ]

defaults:
    GRUB_DISTRIBUTOR: "Arch Modern"
    GRUB_TIMEOUT: 5
    GRUB_DEFAULT: 0
    GRUB_DISABLE_SUBMENU: true
    GRUB_GFXMODE: "auto"
    GRUB_GFXPAYLOAD_LINUX: "keep"
    GRUB_DISABLE_RECOVERY: false
    GRUB_DISABLE_OS_PROBER: false

always_use_defaults: true
