# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
region:                     ""
zone:                       ""
useSystemTimezone:          true
adjustLiveTimezone:         true
useEventIcon:               true
adjustedTimezoneDb:         ""
localeGenPath:              "/etc/default/libc-locales"
geoip:
    style:                  "none"
