# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
region:                     ""
zone:                       ""
useEventIcon:               true
adjustedTimezoneDb:         ""
geoipUrl:                   "https://geoip.kde.org/v1/ubiquity"
