# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
# Disable systemd-machine-id-setup
system: false
# Use dbus-uuidgen to generate machine-id
dbus: true
# Symlink /etc/machine-id to /var/lib/dbus/machine-id (Void Linux standard)
symlink: true
