# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
# Configuration for the packages module.
---
backend: xbps

skip_if_no_internet: false
update_db: false
update_system: false

operations:
  - remove:
    - calamares
