---
efiSystemPartition:     "/boot/efi"
efiSystemPartitionSize: 512M

userSwapChoices:
    - none
    - small
    - suspend
    - file
    - reuse

drawNestedPartitions:   false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none
defaultFileSystemType:  "ext4"
availableFileSystemTypes:
    - "ext4"
    - "btrfs"
    - "xfs"
    - "f2fs"

enableLuksAutomatedPartitioning: true

