---
efi:
    mountPoint:            "/boot/efi"
    recommendedSize:       512M
    minimumSize:            256M
    label:                  "EFI"

userSwapChoices:
    - none
    - small
    - suspend
    - file

drawNestedPartitions:   false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none
defaultFileSystemType:  "ext4"
availableFileSystemTypes:
    - "ext4"
    - "btrfs"
    - "xfs"
    - "f2fs"

enableLuksAutomatedPartitioning: true
luksGeneration:            luks1
allowManualPartitioning:   true
showNotEncryptedBootMessage: true

defaultPartitionTableType:  gpt

directoryFilesystemRestrictions:
    - mountpoint: "/"
      allowedFilesystemTypes: ["ext4", "btrfs", "xfs", "f2fs"]
    - mountpoint: "/boot/efi"
      allowedFilesystemTypes: ["fat32"]

lvm:
    enable: true
