---
# Configure final Void Linux hooks (kernel, initramfs, dkms, etc)
dontChroot: false
timeout: 600
script:
    - command: "echo 'add_dracutmodules+=\" plymouth \"' > /etc/dracut.conf.d/plymouth.conf"
    - command: "LOC=$(cat /etc/locale.conf | grep LANG= | cut -d= -f2) && sed -i \"s|^#\\s*\\(${LOC}\\)|\\1|\" /etc/default/libc-locales || true"
    - command: "/usr/bin/xbps-reconfigure -f glibc-locales"
    - command: "/usr/bin/xbps-reconfigure -fa"
