# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
defaultGroups:
    - wheel
    - audio
    - video
    - storage
    - network
    - input
    - dialout
    - kvm
    - lp
    - lpadmin
    - scanner
    - power
    - optical
    - users

autologinGroup:             autologin
writeUserPasswordToConsole: false
sudoersGroup:               wheel
setRootPassword:            true
userSettingDefaultGroups:   true
allowWeakPasswords:         false
allowWeakPasswordsDefault:  false

