# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
defaultGroups:
    - lp
    - wheel
    - video
    - audio
    - optical
    - storage
    - scanner
    - power
    - users
autologinGroup:             autologin
writeUserPasswordToConsole: false
sudoersGroup:               wheel
setRootPassword:            true
userSettingDefaultGroups:   true
