# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
---
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    true

requirements:
    requiredRAM:        2.0
    requiredDisk:       15.0
    internetCheckUrl:   "https://archlinux.org"
    check:
        - storage
        - ram
        - power
        - internet
        - screen
        - root
    required:
        - storage
        - ram
        - root
