[Seat:*]
autologin-user=live
autologin-user-timeout=0
autologin-session=xfce
user-session=xfce
greeter-session=lightdm-gtk-greeter
display-setup-script=sh -c "command -v plymouth >/dev/null 2>&1 && plymouth --quit || true"

